#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR" -cp "$APPDIR/lib/MultiWiiConf_1_8_patch2.jar:$APPDIR/lib/core.jar:$APPDIR/lib/serial.jar:$APPDIR/lib/RXTXcomm.jar:$APPDIR/lib/controlP5.jar:$APPDIR/lib/opengl.jar:$APPDIR/lib/jogl.jar:$APPDIR/lib/gluegen-rt.jar" MultiWiiConf_1_8_patch2
